# Generated by Django 5.0 on 2023-12-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_booklanguage_alter_book_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='BookAuthor',
        ),
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'verbose_name': 'Автор книги', 'verbose_name_plural': 'Автори книги'},
        ),
        migrations.AlterModelOptions(
            name='booklanguage',
            options={'verbose_name': 'Мова', 'verbose_name_plural': 'Мови'},
        ),
    ]
